# Generated by Django 6.0.7 on 2026-07-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_options_alter_blogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(max_length=3000),
        ),
    ]
