# Generated by Django 6.0.7 on 2026-07-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_comments_created_at_comments_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_body',
            field=models.TextField(max_length=4000),
        ),
    ]
