# Generated by Django 6.0.7 on 2026-07-20 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sideBar', '0002_sociallink_alter_about_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name_plural': 'sociallink'},
        ),
    ]
